global_defs {
    router_id NGINX_LB_MASTER
    script_user root
    enable_script_security
}

vrrp_script check_nginx {
    script "/usr/bin/curl -f http://localhost/health"
    interval 3
    weight -20
    fall 3
    rise 2
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass 1234
    }

    virtual_ipaddress {
        172.28.0.100/16 dev eth0
    }

    track_script {
        check_nginx
    }

    notify_master "/bin/echo 'Transition to MASTER state'"
    notify_backup "/bin/echo 'Transition to BACKUP state'"
    notify_fault "/bin/echo 'Transition to FAULT state'"
}
